# ReLU Activation

In [1]:
import nnfs
from nnfs.datasets import spiral_data
import numpy as np

In [2]:
nnfs.init()

In [3]:
X, y = spiral_data(samples=100, classes=3)

In [4]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [5]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

#### Create Model

In [6]:
dense1 = Layer_Dense(2, 3)

activation1 = Activation_ReLU()
dense1.forward(X)
activation1.forward(dense1.output)

In [7]:
activation1.output[:5]

array([[0.        , 0.        , 0.        ],
       [0.        , 0.00011395, 0.        ],
       [0.        , 0.00031729, 0.        ],
       [0.        , 0.00052666, 0.        ],
       [0.        , 0.00071401, 0.        ]], dtype=float32)

# Softmax Activation

In [8]:
# pg 105
class Activation_Softmax:
    def forward(self, inputs):
        # Get exponentiated normalized probabilities
        # - The subtraction is to help minimize "exploding values"
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        
        # Normalize for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        
        self.output = probabilities
softmax = Activation_Softmax()
softmax.forward([[1, 2, 3]])
print(softmax.output)

[[0.09003057 0.24472847 0.66524096]]


#### Create Model

In [9]:
dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()
dense1.forward(X)

activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333343 0.33333343 0.33333316]
 [0.33333352 0.3333335  0.33333296]
 [0.33333352 0.3333335  0.33333296]
 [0.3333336  0.33333358 0.33333278]]
